title: Yersultan Doszhan
description: >-
  Software engineer and CS student at KAIST.
author: Yersultan Doszhan
email: yersultanofficial@gmail.com
url: "https://edoszhan.github.io"
baseurl: ""
theme: minima
github_username: edoszhan
header_pages:
  - index.md
  - cv.md
  - publications.md
  - projects.md
  - blog.md
plugins:
  - jekyll-seo-tag
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  silence_deprecations: ['import']
